version: '3.8'

services:
  # Frontend service (React app)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feedaq-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - feedaq-network
    restart: unless-stopped

  # Backend service (Node.js API)
  backend:
    build:
      context: ../feedaq-academy-backend
      dockerfile: Dockerfile
    container_name: feedaq-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - feedaq-network
    restart: unless-stopped
    volumes:
      # Mount a volume for logs if needed
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  feedaq-network:
    driver: bridge

volumes:
  logs:
    driver: local